config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  
  resources :users do
    resources :loans
  end
  get '/home/automatic_payments' => 'home#automatic_payments', as: 'automatic_payments'

 end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/campaign.rb
class Campaign < ApplicationRecord
  has_many :loans
  has_many :investors, through: :loans, class_name: "User" 
end

app/models/loan.rb
class Loan < ApplicationRecord
  belongs_to :campaign
  belongs_to :investor, class_name: "User"
  has_many :payments

  def amount_paid
    payments = self.payments
    amount_paid = 0
    payments.each do |payment|
      amount_paid += payment.amount_paid
    end
    amount_paid
  end

  def schedule
    scheduled_payments = PaymentScheduler.expected_schedule(self)
  end

  def late_payments
    late_payments = PaymentScheduler.late_payments(self) 
  end


end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :loan

end

app/models/user.rb
class User < ApplicationRecord
  has_many :loans, foreign_key: "investor_id"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    @user = User.first
  end
  
  def automatic_payments
    @user = User.first
  end

end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  before_action :select_loan, only: [:show]
  
  def show
    @schedule = @loan.schedule
    @late_payments = @loan.late_payments
    respond_to do |format|
      format.js
    end
  end

private
  def select_loan
    @loan = Loan.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/automatic_payments.html.erb
<div class= "col-md-12">
  <div class="panel panel-primary">
    <div class="panel-heading">Autopilot feature</div>
      <div class="panel-body">
        My biggest concern with the current layout for the autopilot feature is the slider. Instead, I would give users a visual cue that is more intuitive, specifically, a responsive pie chart aligned in the left column that would be allocated into three different colored categories: low risk, medium risk, and high risk. The center panel would be similar to the way it is laid out now, however, instead of the slider it would include forms or buttons, so that the user can enter the allocation percentage for each category and the pie chart would respond with a visual representation of their alloction.

        I would also include, in a separate column on the right side of the window, a list of campaigns that fall into each risk category and that meet their autopilot critera. This would allow users to see rather than assume which types of campaigns their autopilot allocation would invest in.

        Finally, I would make a minor change to the category "Maximum invested in each campaign as percentage of campaign size". This feature, although important, may be difficult for users to understand or feel comfortable entering a specific amount for. Instead, I would use predefined percentages as radio buttons. I think this would reduce user anxiety. 
      </div>
    </div>
  </div>

app/views/home/index.html.erb
<div class="row">
  <div class= "col-xs-12 col-md-4">
    <h2>Loans</h2>
      <table class="table table-condensed">
        <% @user.loans.each do |loan| %>
          <tr>
            <td><%= link_to loan.campaign.description, user_loan_path(loan.investor, loan), remote: true %>: <%= loan.amount %></td>
          </tr>
        <% end %>
      </table>
  </div>

  <div class="loan-window">
  </div>
  
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LenderPortfolio</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <ul class="nav nav-tabs">
        <li role="presentation"><%= link_to 'Portfolio', root_path %></li>
        <li role="presentation"><%= link_to 'Automatic Payments', automatic_payments_path %></li>
      </ul>

    <div class="jumbotron">
      <h1>Hello, <%= @user.name %>!</h1>
      <p>This is your loan portfolio</p>
    </div>      
      <%= yield %>
    </div>
  </body>
</html>

app/views/loans/_show.html.erb
<div class="loan-content">
  <div class= "col-xs-6 col-md-4">
    <h2>Payment Schedule</h2>
    <div>
    <span class="label label-success">Paid On-Time</span>
    <span class="label label-warning">Paid Late</span>
    <span class="label label-danger">Unpaid and Late</span>
    </div><br>
      <table class="table table-condensed">
        <tr>
          <th>#</th>
          <th>Due on:</th>
          <th>Amount Due:</th>
          <th>Amount Paid:</th>
        </tr>
        <% @schedule.each do |entry| %>
          <% if entry[:late] && entry[:paid]%>
            <tr class="warning">
          <% elsif entry[:late] %>
            <tr class="danger">
          <% elsif entry[:paid]%>
            <tr class="success">
          <% else %>  
          <tr>
            <% end %>
            <td><%= entry[:payment_period] %></td>
            <td><%= entry[:due_date] %></td>
            <td><%= entry[:amount_due] %></td>
            <td><%= entry[:amount_paid] %></td>
          </tr>
        <% end %>
      </table>  
  </div>

  <div class= "col-xs-6 col-md-4">
    <h2>Late Payments</h2>
    <table class="table table-condensed">
        <tr>
          <th>&#60 10 days</th>
          <th>10-20 days</th>
          <th>20+</th>
        </tr>
        <tr>
          <td><%= @late_payments[:less_than_ten_days_late] %></td>
          <td><%= @late_payments[:up_to_twenty_days_late] %></td>
          <td><%= @late_payments[:more_than_twenty_days_late] %></td>
        </tr>
    </table>
    </div>

app/views/loans/show.js.erb
$(".loan-content").remove()

$(".loan-window").append("<%= j render :partial => 'loans/show' %>").hide().fadeIn()